apiVersion: v1
kind: Service
metadata:
  labels:
    jvm: prometheus
  name: jvm-prometheus
spec:
  ports:
  - name: jvm
    port: 65533
    protocol: TCP
    targetPort: 65533
  selector:
    jvm: prometheus
  type: ClusterIP
